// const fakeDb = [
//     {id: 1, name:'Online Courses', descripition:'Learn flexibly with online degree courses created by leading universities. From undergraduate to postgraduate, make degree-level learning work for you.', image:'https://media.istockphoto.com/vectors/elearning-online-school-vector-background-elearning-online-courses-vector-id1222531912' },
//     {id: 2, name:'Start Date', descripition:'"Start date" is more common among American English speakers, while more BrE speakers use "starting date." "Starting date" is not wrong.', image:'https://qph.fs.quoracdn.net/main-qimg-b0268e56866f71dcbff815f4d02256ec' },
//     {id: 3, name:'Unlimited tabs', descripition:'Learn flexibly with online degree courses created by leading universities. From undergraduate to postgraduate, make degree-level learning work for you.', image:'https://www.which-addon.com/wp-content/uploads/2020/08/Tabs-Widget-for-Elementor.png' },
//     {id: 4, name:'Open Library', descripition:'Open Library is an online project intended to create "one web page for every book ever published".Open Library is a project of the Internet Archive, a nonprofit organization.', image:'https://covinaca.gov/sites/default/files/imageattachments/wysiwyg/openlibrary-banner2.jpg' },
//     {id: 5, name:'Ready to Use', descripition:'In addition to being the number one-selling easy-to-use database software, the award-winning FileMaker product line also includes low-cost Applications that automate basic business tasks, ready-to-use Starter Solutions.', image:'https://comps.canstockphoto.com/ready-to-use-vector-sign-eps-vector_csp85599249.jpg' },
//     {id: 6, name:'Measurable', descripition:'A condition characterised by a lesion or tumour that can be measured in size, which is used to evaluate response to treatment.', image:'https://cdn.business2community.com/wp-content/uploads/2016/11/Formulate-a-Targeted-and-Measurable-Marketing-Goal.jpg' },
//     {id: 7, name:'Everywhere', descripition:'Curabitur ultrices quam vulputate libero elementum pulvinar. Phasellus gravida enim, sit amet congue lectus ullamcorper sed. Aliquam est eu fermentum.', image:'https://absolutemail.com/wp-content/uploads/2020/11/Cloud-and-IOT2-1024x682-1.jpg' },
//     {id: 8, name:'Related Course', descripition:'A related course is simply a course that is in a course list that is published somewhere pointing students to it for specific purposes. Students enroll in the course.', image:'https://www.re-thinkingthefuture.com/wp-content/uploads/2020/08/A1596-15-related-skills-architectural-students-can-acquire-during-their-academic-course..jpg' },
//     {id: 9, name:'Certificated', descripition:'In use, however, certificated seems to belong to the educational sphere, while certified is the word used to describe standards and qualifications in other occupations and industries. ', image:'https://www.ceaa.co.uk/_webedit/cached-images/33.png' }
// ]